const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs');
const path = require('path');
const { extractPages } = require('./pdfPageExtractor');

const MODEL_PRICING = {
  'claude-haiku-4-5-20251001': { input: 1.00, output: 5.00, cache: 0.10 },
  'claude-sonnet-4-5-20250929': { input: 3.00, output: 15.00, cache: 0.30 }
};

/**
 * Convert PDF or image to DOCX using Claude API with docx skill
 * (Matching Python backend approach - no code generation!)
 * @param {Buffer} pdfBuffer - PDF or image file buffer
 * @param {string} jobId - Job ID
 * @param {Object} settings - Conversion settings (includes mimeType for detecting file type)
 * @param {JobManager} jobManager - Job manager instance
 */
async function convertPdf(pdfBuffer, jobId, settings, jobManager) {
  const workDir = `/tmp/conversion-${jobId}`;
  const enableLogging = settings.enableLogging || false;

  const log = (message) => {
    if (enableLogging) {
      console.log(`[${jobId}] ${message}`);
    }
  };

  try {
    // Step 1: Setup workspace
    jobManager.updateJob(jobId, {
      status: 'processing',
      progress: 10,
      currentStep: 'Setting up workspace'
    });

    fs.mkdirSync(workDir, { recursive: true });
    log('Workspace created');

    // Detect if this is an image or PDF
    const mimeType = settings.mimeType || 'application/pdf';
    const isImage = mimeType.startsWith('image/');
    const fileType = isImage ? 'image' : 'document';

    // Step 2: Extract specific pages if page range is specified (PDFs only)
    let processedPdfBuffer = pdfBuffer;
    if (!isImage && settings.pageRange && settings.pageRange.trim() !== '') {
      jobManager.updateJob(jobId, {
        progress: 15,
        currentStep: 'Extracting pages'
      });

      try {
        processedPdfBuffer = await extractPages(pdfBuffer, settings.pageRange);
        log(`Extracted pages: ${settings.pageRange}`);
      } catch (error) {
        throw new Error(`Page extraction failed: ${error.message}`);
      }
    }

    // Step 3: Encode file as base64
    jobManager.updateJob(jobId, {
      progress: 20,
      currentStep: isImage ? 'Encoding image' : 'Encoding PDF'
    });

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new Error('ANTHROPIC_API_KEY not configured');
    }

    const anthropic = new Anthropic({ apiKey });

    // Convert processed buffer to base64
    const fileBase64 = processedPdfBuffer.toString('base64');
    log(`${isImage ? 'Image' : 'PDF'} encoded (${fileBase64.length} chars)`);

    // Step 4: Build prompt (simplified - matching Python backend)
    jobManager.updateJob(jobId, {
      progress: 30,
      currentStep: 'Preparing conversion'
    });

    const prompt = isImage ? buildImagePrompt(settings) : buildPrompt(settings);

    // Step 5: Call Claude API with docx skill
    jobManager.updateJob(jobId, {
      progress: 40,
      currentStep: 'Processing with Claude + docx skill'
    });

    const model = settings.model || 'claude-haiku-4-5-20251001';
    log(`Calling Claude API with ${model} and docx skill (streaming)`);
    const startTime = Date.now();

    const stream = anthropic.beta.messages.stream({
      model,
      max_tokens: 32000,
      betas: [
        'code-execution-2025-08-25',
        'skills-2025-10-02'
      ],
      container: {
        skills: [{
          type: 'anthropic',
          skill_id: 'docx',
          version: 'latest'
        }]
      },
      messages: [{
        role: 'user',
        content: [
          {
            type: fileType,  // 'image' or 'document'
            source: {
              type: 'base64',
              media_type: mimeType,  // e.g., 'image/jpeg' or 'application/pdf'
              data: fileBase64
            },
            cache_control: { type: 'ephemeral' }
          },
          {
            type: 'text',
            text: prompt
          }
        ]
      }],
      tools: [{
        type: 'code_execution_20250825',
        name: 'code_execution'
      }]
    });

    // Handle streaming events
    stream.on('text', (textDelta) => {
      log(`Claude: ${textDelta}`);
    });

    stream.on('content_block_delta', (delta) => {
      if (delta.type === 'input_json_delta') {
        log('Tool input delta received');
      }
    });

    // Wait for completion
    const response = await stream.finalMessage();

    const apiTime = ((Date.now() - startTime) / 1000).toFixed(1);
    log(`API responded in ${apiTime}s`);

    // Step 6: Extract generated file
    jobManager.updateJob(jobId, {
      progress: 70,
      currentStep: 'Extracting result'
    });

    const generatedFileId = extractFileId(response);

    if (!generatedFileId) {
      console.error(`[${jobId}] No file generated. Response:`, JSON.stringify(response.content, null, 2));
      throw new Error('No DOCX file generated by docx skill');
    }

    log(`File generated: ${generatedFileId}`);

    // Step 7: Download the generated DOCX
    jobManager.updateJob(jobId, {
      progress: 85,
      currentStep: 'Downloading result'
    });

    const fileMetadata = await anthropic.beta.files.retrieveMetadata(
      generatedFileId,
      { betas: ['files-api-2025-04-14'] }
    );

    const fileContent = await anthropic.beta.files.download(
      generatedFileId,
      { betas: ['files-api-2025-04-14'] }
    );

    const outputPath = path.join(workDir, fileMetadata.filename || 'converted.docx');

    // Convert Response to Buffer
    const arrayBuffer = await fileContent.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    fs.writeFileSync(outputPath, buffer);

    log(`Downloaded: ${fileMetadata.filename}`);

    // Step 8: Calculate cost
    const inputTokens = response.usage.input_tokens;
    const outputTokens = response.usage.output_tokens;
    const cachedTokens = response.usage.cache_read_input_tokens || 0;
    const cacheCreationTokens = response.usage.cache_creation_input_tokens || 0;

    const pricing = MODEL_PRICING[model] || MODEL_PRICING['claude-haiku-4-5-20251001'];
    const cost = (inputTokens / 1_000_000) * pricing.input +
                 (outputTokens / 1_000_000) * pricing.output +
                 (cachedTokens / 1_000_000) * pricing.cache +
                 (cacheCreationTokens / 1_000_000) * pricing.input; // Cache creation charged at input rate

    // Always log token usage (not just when enableLogging is on)
    console.log(`[${jobId}] Tokens: ${inputTokens} input, ${outputTokens} output`);
    if (cacheCreationTokens > 0) {
      console.log(`[${jobId}] Cache: ${cacheCreationTokens} created (first time - future conversions will be 90% cheaper!)`);
    }
    if (cachedTokens > 0) {
      const savedCost = (cachedTokens / 1_000_000) * (pricing.input - pricing.cache);
      console.log(`[${jobId}] Cache: ${cachedTokens} read (saved $${savedCost.toFixed(4)}!)`);
    }
    console.log(`[${jobId}] Cost: $${cost.toFixed(4)}`);

    // Step 9: Complete
    jobManager.updateJob(jobId, {
      status: 'completed',
      progress: 100,
      currentStep: 'Complete',
      outputPath,
      inputTokens,
      outputTokens,
      actualCost: cost,
      completedAt: Date.now()
    });

    const totalTime = ((Date.now() - startTime) / 1000).toFixed(1);
    log(`✓ Conversion complete (${totalTime}s total)`);

    // Cleanup after 5 minutes
    setTimeout(() => {
      if (fs.existsSync(workDir)) {
        fs.rmSync(workDir, { recursive: true, force: true });
      }
      jobManager.deleteJob(jobId);
    }, 5 * 60 * 1000);

  } catch (error) {
    console.error(`[${jobId}] Conversion failed:`, error.message);
    if (error.response) {
      console.error(`[${jobId}] API error details:`, error.response);
    }

    jobManager.updateJob(jobId, {
      status: 'failed',
      error: error.message
    });

    // Cleanup on error
    if (fs.existsSync(workDir)) {
      fs.rmSync(workDir, { recursive: true, force: true });
    }

    throw error;
  }
}

/**
 * Build conversion prompt optimized for complex documents (academic transcripts, tables)
 */
function buildPrompt(settings) {
  const {
    font = 'Arial',
    fontSize = 12,
    margins = {},
    preserveTableFormatting = true,
    addPageMarkers = false,
    replaceSignatures = false,
    overrideFormatting = false,
    customInstructions = ''
  } = settings;

  let prompt = `Convert this PDF document to professional Word format (.docx) using the docx skill.

## Formatting Requirements
`;

  if (preserveTableFormatting) {
    prompt += `**TABLES (CRITICAL for academic transcripts):**
- Preserve ALL table structures with EXACT column and row layout
- Maintain precise borders, gridlines, and cell spacing
- Keep cell merging/spanning exactly as shown
- Preserve header rows with proper formatting
- Maintain column widths proportionally
- DO NOT convert tables to text - keep as actual Word tables

`;
  }

  if (overrideFormatting) {
    const marginTop = (margins.top || 1440) / 1440;
    const marginRight = (margins.right || 1440) / 1440;
    const marginBottom = (margins.bottom || 1440) / 1440;
    const marginLeft = (margins.left || 1440) / 1440;

    prompt += `**OVERRIDE FORMATTING (User-specified):**
- Apply ${font} ${fontSize}pt font throughout document
- Set margins: Top ${marginTop}", Right ${marginRight}", Bottom ${marginBottom}", Left ${marginLeft}"
- Override original formatting with these custom settings
`;
  } else {
    prompt += `**PRESERVE ORIGINAL FORMATTING:**
- Preserve original fonts, sizes, and styles exactly
- Preserve original margins from source document
- Maintain bold, italic, underline as in source
`;
  }

  prompt += `
## Special Instructions
`;

  if (addPageMarkers) {
    prompt += `- Insert page markers: "[Page X of original document:]" at END of complete sentences after page breaks
- Example: "...end of paragraph on page 1. [Page 2 of original document:] Start of next page..."
- NEVER insert mid-sentence (breaks CAT tool segmentation)
`;
  }

  if (replaceSignatures) {
    prompt += `- Replace signature images with text placeholder: [Signature]
`;
  }

  if (customInstructions) {
    prompt += `- Custom: ${customInstructions}
`;
  }

  prompt += `
## CRITICAL VERIFICATION REQUIREMENTS

**Before generating code, verify:**
1. ✓ Read ENTIRE document - scan ALL pages, do not skip any sections
2. ✓ Preserve EXACT text - no paraphrasing, no summarizing, no interpretation
3. ✓ Reproduce EXACT formatting - use actual font sizes, not "Heading" styles unless explicitly shown
4. ✓ Include ALL elements - text, tables, images, footnotes, headers, footers

**Anti-Hallucination Rules:**
- ❌ DO NOT add content that isn't visible in the source document
- ❌ DO NOT interpret or summarize - reproduce character-for-character
- ❌ DO NOT skip sections because they appear repetitive or similar
- ❌ DO NOT add titles, section numbers, or labels not in original
- ❌ DO NOT merge or combine tables - keep each table separate

**For Complex Tables (academic transcripts, financial statements):**
- Count columns and rows in source - output must match exactly
- Preserve alignment (left/center/right) for each cell
- Maintain number formatting (decimals, percentages, dates)
- Keep merged cells in exact positions
- Preserve table headers and repeat if needed across pages

**Completeness Check (MANDATORY):**
After generating document:
1. Count pages in source → verify all pages included in output
2. Count tables → verify all tables reproduced
3. Verify no text blocks were omitted
4. Confirm document ends at same point as source

**Output Requirements:**
- Use the docx skill to create a complete .docx file
- Process ALL pages completely
- Print confirmation when done

**Remember:** For academic transcripts and official documents, PERFECT accuracy is required. Every cell, every number, every line must match the source exactly.
`;

  return prompt;
}

/**
 * Build conversion prompt for images
 */
function buildImagePrompt(settings) {
  const {
    font = 'Arial',
    fontSize = 12,
    margins = {},
    overrideFormatting = false,
    customInstructions = ''
  } = settings;

  let prompt = `Convert this image to a professional Word document (.docx) using the docx skill.

## Task
Extract ALL text and visual elements from this image and create a properly formatted Word document that reproduces the content with high fidelity.

## Formatting Requirements
`;

  if (overrideFormatting) {
    const marginTop = (margins.top || 1440) / 1440;
    const marginRight = (margins.right || 1440) / 1440;
    const marginBottom = (margins.bottom || 1440) / 1440;
    const marginLeft = (margins.left || 1440) / 1440;

    prompt += `**OVERRIDE FORMATTING (User-specified):**
- Apply ${font} ${fontSize}pt font throughout document
- Set margins: Top ${marginTop}", Right ${marginRight}", Bottom ${marginBottom}", Left ${marginLeft}"
- Use these custom settings instead of preserving original
`;
  } else {
    prompt += `**PRESERVE ORIGINAL FORMATTING:**
- Preserve text layout, alignment, and formatting as shown in the image
- Maintain font sizes proportionally as they appear in the image
- Preserve original spacing and margins from the image
`;
  }

  prompt += `- If the image contains tables, reproduce them as actual Word tables
- If the image contains lists, use proper list formatting
- Preserve visual hierarchy (headings, subheadings, body text)

## Special Instructions
`;

  if (customInstructions) {
    prompt += `- Custom: ${customInstructions}\n`;
  }

  prompt += `
## Critical Requirements
1. ✓ Extract ALL text visible in the image - do not skip any content
2. ✓ Preserve EXACT text - no paraphrasing, no summarizing
3. ✓ Reproduce formatting - maintain alignment, spacing, and emphasis (bold/italic)
4. ✓ Include ALL elements - text, tables, lists, visual structure

**Anti-Hallucination Rules:**
- ❌ DO NOT add content that isn't visible in the image
- ❌ DO NOT interpret or summarize - reproduce character-for-character
- ❌ DO NOT skip sections because they appear repetitive

**Output Requirements:**
- Use the docx skill to create a complete .docx file
- Process the entire image completely
- Print confirmation when done

**Remember:** PERFECT accuracy is required. Every word, every element must match the source image exactly.
`;

  return prompt;
}

/**
 * Extract file ID from Claude response
 * Uses multiple strategies (matching Python backend)
 */
function extractFileId(response) {
  // Strategy 1: Check bash_code_execution_tool_result
  for (const item of response.content) {
    if (item.type === 'bash_code_execution_tool_result') {
      const content = item.content;
      if (content && content.type === 'bash_code_execution_result') {
        for (const file of content.content || []) {
          if (file.file_id) {
            return file.file_id;
          }
        }
      }
    }
  }

  // Strategy 2: Check text content for file IDs
  for (const item of response.content) {
    if (item.type === 'text' && item.text) {
      const match = item.text.match(/file-[a-zA-Z0-9_-]{20,}/);
      if (match) {
        return match[0];
      }
    }
  }

  // Strategy 3: Deep inspection
  const jsonStr = JSON.stringify(response.content);
  const match = jsonStr.match(/file-[a-zA-Z0-9_-]{20,}/);
  if (match) {
    return match[0];
  }

  return null;
}

module.exports = { convertPdf };
