const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs');
const path = require('path');

const MODEL_PRICING = {
  'claude-haiku-4-5-20251001': { input: 1.00, output: 5.00, cache: 0.10 },
  'claude-sonnet-4-5-20250929': { input: 3.00, output: 15.00, cache: 0.30 }
};

/**
 * Convert PDF to DOCX using Claude API with docx skill
 * (Matching Python backend approach - no code generation!)
 * @param {Buffer} pdfBuffer - PDF file buffer
 * @param {string} jobId - Job ID
 * @param {Object} settings - Conversion settings
 * @param {JobManager} jobManager - Job manager instance
 */
async function convertPdf(pdfBuffer, jobId, settings, jobManager) {
  const workDir = `/tmp/conversion-${jobId}`;
  const enableLogging = settings.enableLogging || false;

  const log = (message) => {
    if (enableLogging) {
      console.log(`[${jobId}] ${message}`);
    }
  };

  try {
    // Step 1: Setup workspace
    jobManager.updateJob(jobId, {
      status: 'processing',
      progress: 10,
      currentStep: 'Setting up workspace'
    });

    fs.mkdirSync(workDir, { recursive: true });
    log('Workspace created');

    // Step 2: Upload PDF to Claude Files API
    jobManager.updateJob(jobId, {
      progress: 20,
      currentStep: 'Uploading PDF to Claude'
    });

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new Error('ANTHROPIC_API_KEY not configured');
    }

    const anthropic = new Anthropic({ apiKey });

    // Save buffer to temp file for upload
    const tempPdfPath = path.join(workDir, 'input.pdf');
    fs.writeFileSync(tempPdfPath, pdfBuffer);

    const fileUpload = await anthropic.beta.files.upload({
      file: fs.createReadStream(tempPdfPath),
      purpose: 'user_upload'
    }, {
      betas: ['files-api-2025-04-14']
    });

    const fileId = fileUpload.id;
    log(`Uploaded PDF as file ID: ${fileId}`);

    // Step 3: Build prompt (simplified - matching Python backend)
    jobManager.updateJob(jobId, {
      progress: 30,
      currentStep: 'Preparing conversion'
    });

    const prompt = buildPrompt(settings);

    // Step 4: Call Claude API with docx skill
    jobManager.updateJob(jobId, {
      progress: 40,
      currentStep: 'Processing with Claude + docx skill'
    });

    const model = settings.model || 'claude-haiku-4-5-20251001';
    log(`Calling Claude API with ${model} and docx skill`);
    const startTime = Date.now();

    const response = await anthropic.beta.messages.create({
      model,
      max_tokens: 32000,
      betas: [
        'code-execution-2025-08-25',
        'skills-2025-10-02',
        'files-api-2025-04-14'
      ],
      container: {
        skills: [{
          type: 'anthropic',
          skill_id: 'docx',
          version: 'latest'
        }]
      },
      messages: [{
        role: 'user',
        content: [
          {
            type: 'document',
            source: {
              type: 'file',
              file_id: fileId
            }
          },
          {
            type: 'text',
            text: prompt
          }
        ]
      }],
      tools: [{
        type: 'code_execution_20250825',
        name: 'code_execution'
      }]
    });

    const apiTime = ((Date.now() - startTime) / 1000).toFixed(1);
    log(`API responded in ${apiTime}s`);

    // Step 5: Extract generated file
    jobManager.updateJob(jobId, {
      progress: 70,
      currentStep: 'Extracting result'
    });

    const generatedFileId = extractFileId(response);

    if (!generatedFileId) {
      console.error(`[${jobId}] No file generated. Response:`, JSON.stringify(response.content, null, 2));
      throw new Error('No DOCX file generated by docx skill');
    }

    log(`File generated: ${generatedFileId}`);

    // Step 6: Download the generated DOCX
    jobManager.updateJob(jobId, {
      progress: 85,
      currentStep: 'Downloading result'
    });

    const fileMetadata = await anthropic.beta.files.retrieveMetadata(
      generatedFileId,
      { betas: ['files-api-2025-04-14'] }
    );

    const fileContent = await anthropic.beta.files.download(
      generatedFileId,
      { betas: ['files-api-2025-04-14'] }
    );

    const outputPath = path.join(workDir, fileMetadata.filename || 'converted.docx');

    // Write the file using .read() method
    const buffer = fileContent.read();
    fs.writeFileSync(outputPath, buffer);

    log(`Downloaded: ${fileMetadata.filename}`);

    // Step 7: Calculate cost
    const inputTokens = response.usage.input_tokens;
    const outputTokens = response.usage.output_tokens;
    const cachedTokens = response.usage.cache_read_input_tokens || 0;

    const pricing = MODEL_PRICING[model] || MODEL_PRICING['claude-haiku-4-5-20251001'];
    const cost = (inputTokens / 1_000_000) * pricing.input +
                 (outputTokens / 1_000_000) * pricing.output +
                 (cachedTokens / 1_000_000) * pricing.cache;

    log(`Tokens: ${inputTokens} input, ${outputTokens} output, ${cachedTokens} cached`);
    log(`Cost: $${cost.toFixed(4)}`);

    // Step 8: Complete
    jobManager.updateJob(jobId, {
      status: 'completed',
      progress: 100,
      currentStep: 'Complete',
      outputPath,
      inputTokens,
      outputTokens,
      actualCost: cost,
      completedAt: Date.now()
    });

    const totalTime = ((Date.now() - startTime) / 1000).toFixed(1);
    log(`✓ Conversion complete (${totalTime}s total)`);

    // Cleanup after 5 minutes
    setTimeout(() => {
      if (fs.existsSync(workDir)) {
        fs.rmSync(workDir, { recursive: true, force: true });
      }
      jobManager.deleteJob(jobId);
    }, 5 * 60 * 1000);

  } catch (error) {
    console.error(`[${jobId}] Conversion failed:`, error.message);
    if (error.response) {
      console.error(`[${jobId}] API error details:`, error.response);
    }

    jobManager.updateJob(jobId, {
      status: 'failed',
      error: error.message
    });

    // Cleanup on error
    if (fs.existsSync(workDir)) {
      fs.rmSync(workDir, { recursive: true, force: true });
    }

    throw error;
  }
}

/**
 * Build conversion prompt (simplified - matching Python backend)
 */
function buildPrompt(settings) {
  const {
    font = 'Arial',
    fontSize = 12,
    margins = {},
    preserveTableFormatting = true,
    addPageMarkers = false,
    replaceSignatures = false,
    overrideFormatting = false
  } = settings;

  let prompt = `Convert this document to Word (.docx) format.

**Output Settings:**`;

  if (overrideFormatting) {
    const marginTop = (margins.top || 1440) / 1440; // Convert DXA to inches
    const marginBottom = (margins.bottom || 1440) / 1440;
    const marginLeft = (margins.left || 1440) / 1440;
    const marginRight = (margins.right || 1440) / 1440;

    prompt += `
- Font: ${font} ${fontSize}pt
- Margins: Top ${marginTop}", Bottom ${marginBottom}", Left ${marginLeft}", Right ${marginRight}"`;
  } else {
    prompt += `
- Preserve original formatting exactly`;
  }

  prompt += `

**Text Extraction:**
- Extract all text exactly as shown (no paraphrasing)
- Preserve original language
- Process EVERY PAGE (critical - do not stop after page 1)`;

  if (preserveTableFormatting) {
    prompt += `

**Table Handling (CRITICAL):**
- Preserve exact table structure
- Maintain merged cells, borders, and formatting
- Keep column widths proportional to original`;
  }

  if (addPageMarkers) {
    prompt += `

**Page Markers:**
- Add [Page 2 of original document:], [Page 3 of original document:], etc.
- Start from page 2 (not page 1)`;
  }

  if (replaceSignatures) {
    prompt += `

**Signatures:**
- Replace signature images with text: [Signature]`;
  }

  prompt += `

**Generate Document:**
Use the docx skill to create a professional Word document.`;

  return prompt;
}

/**
 * Extract file ID from Claude response
 * Uses multiple strategies (matching Python backend)
 */
function extractFileId(response) {
  // Strategy 1: Check bash_code_execution_tool_result
  for (const item of response.content) {
    if (item.type === 'bash_code_execution_tool_result') {
      const content = item.content;
      if (content && content.type === 'bash_code_execution_result') {
        for (const file of content.content || []) {
          if (file.file_id) {
            return file.file_id;
          }
        }
      }
    }
  }

  // Strategy 2: Check text content for file IDs
  for (const item of response.content) {
    if (item.type === 'text' && item.text) {
      const match = item.text.match(/file-[a-zA-Z0-9_-]{20,}/);
      if (match) {
        return match[0];
      }
    }
  }

  // Strategy 3: Deep inspection
  const jsonStr = JSON.stringify(response.content);
  const match = jsonStr.match(/file-[a-zA-Z0-9_-]{20,}/);
  if (match) {
    return match[0];
  }

  return null;
}

module.exports = { convertPdf };
